In [12]:
import pandas as pd
import os
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [13]:
# Path con los datasets iniciales
#os.chdir('D:/Documents/UPM/Actual/TFG/LEMD/DataSets')
#os.chdir('C:/Users/aalfaro/Documents/Meteo/TFG/LEMD/DataSets')

os.chdir('/home/crida/notebooks/Meteo TFG Adrian/Datasets')

#pd.options.display.max_rows = 200
#pd.options.display.max_columns = 50

#pd.set_option('display.float_format', lambda x: '%.10f' % x)

In [14]:
# Dataset con la información de separación
r32_df = pd.read_csv('Runway32.csv', header = 0, decimal = ',', sep = ';')

r32_df = r32_df.drop(['date', 'dateTime', 'next_dateTime', 'arr_volume_group', 'runway', 'flight_key', 'metarKey', 'maxKnots'], axis=1)

r32_df.loc[(r32_df['m4_altitude'] == '27+'), 'm4_altitude'] = 27
r32_df = r32_df.astype({'m4_altitude': 'float64'})

enc = OrdinalEncoder(categories = [['L', 'M', 'H', 'J']])
r32_df.loc[:, ['flight_wake']] = enc.fit_transform(r32_df[['flight_wake']])

enc = OrdinalEncoder(categories = [['Front', 'DFront', 'DTail', 'Lateral', 'Tail']])
r32_df.loc[:, ['direction']] = enc.fit_transform(r32_df[['direction']])

r32_df

,threshold_separation,flight_wake,diag_distance,m4_speed,m4_altitude,visibility,CAVOK,temperature,qnh,variable,...,min_height,max_amount,max_amount_height,significantClouds,anyClouds,Lluvia,Niebla,Tormenta,shear,coverage
0,4.549984,1.0,10.312750,131.333,25.0,9999.0,1,-2,1032,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1,7.301271,1.0,4.035634,145.843,22.0,9999.0,1,-2,1032,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
2,11.165620,1.0,3.086627,140.565,20.0,9999.0,1,-2,1032,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
3,4.485055,2.0,7.415822,136.749,20.0,9999.0,1,-2,1032,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,4.462536,1.0,2.672174,134.563,19.0,9999.0,1,-2,1032,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55222,6.137123,1.0,3.388313,137.927,23.0,9999.0,1,4,1031,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
55223,6.956980,1.0,18.181210,154.026,25.0,9999.0,1,4,1031,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
55224,5.514888,1.0,13.279740,149.206,22.0,9999.0,1,4,1031,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
55225,4.829517,1.0,12.476290,139.120,23.0,9999.0,1,4,1031,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0
55226,5.864628,1.0,9.634670,150.526,22.0,9999.0,1,4,1031,0,...,999.0,0.0,999.0,0,1.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Dataset con la información de separación
r18_df = pd.read_csv('Runway18.csv', header = 0, decimal = ',', sep = ';')

r18_df = r18_df.drop(['date', 'dateTime', 'next_dateTime', 'arr_volume_group', 'runway', 'flight_key', 'metarKey', 'maxKnots'], axis=1)

r18_df.loc[(r18_df['m4_altitude'] == '27+'), 'm4_altitude'] = 27
r18_df = r18_df.astype({'m4_altitude': 'float64'})

enc = OrdinalEncoder(categories = [['L', 'M', 'H', 'J']])
r18_df.loc[:, ['flight_wake']] = enc.fit_transform(r18_df[['flight_wake']])

enc = OrdinalEncoder(categories = [['Front', 'DFront', 'DTail', 'Lateral', 'Tail']])
r18_df.loc[:, ['direction']] = enc.fit_transform(r18_df[['direction']])

#r18_df

In [5]:
pd.DataFrame(r32_df.var())

                                  0
threshold_separation       3.458930
flight_wake                0.123065
diag_distance             11.537229
m4_speed                 118.738058
m4_altitude                4.760490
visibility            746598.153907
CAVOK                      0.223603
temperature               72.563061
qnh                       35.153733
variable                   0.121225
direction                  1.731563
knots                     16.420830
knotsVariability           0.899514
min_height_amount          0.642415
min_height            199383.302656
max_amount                 0.984045
max_amount_height     197195.440017
significantClouds          0.023365
anyClouds                  0.000000
Lluvia                     0.043169
Niebla                     0.061179
Tormenta                   0.005983
shear                      0.013590
coverage                   0.149858

In [6]:
X = r32_df.drop(['threshold_separation'], axis=1)
y = r32_df['threshold_separation']

In [7]:
# Estandarizacion
a = StandardScaler().fit_transform(X)
ss_df = pd.DataFrame(data = a, columns = X.columns)

In [8]:
# PCA Estandarizado
pca = PCA(n_components = 10)
pca_a = pca.fit_transform(ss_df)
pca_df = pd.DataFrame(data = pca_a, columns = ['C1','C2','C3','C4','C5','C6','C7','C8','C9','C10'])
#pca_df = pd.DataFrame(data = pca_a)

In [11]:
# Generacion test-train
X_train, X_test, y_train, y_test = train_test_split(ss_df, y, shuffle=True, train_size = 0.7)

# Random Forest Regression
model = RandomForestRegressor(n_estimators = 100)
model.fit(X_train, y_train)

prediction = model.predict(X_test)

pd.DataFrame(data = model.feature_importances_, index = X_train.columns)

                          0
flight_wake        0.019746
diag_distance      0.384590
m4_speed           0.144751
m4_altitude        0.064946
visibility         0.004218
CAVOK              0.003367
temperature        0.098332
qnh                0.086710
variable           0.010004
direction          0.038652
knots              0.068574
knotsVariability   0.004624
min_height_amount  0.009456
min_height         0.020128
max_amount         0.008820
max_amount_height  0.020475
significantClouds  0.004031
anyClouds          0.000000
Lluvia             0.002229
Niebla             0.001004
Tormenta           0.000177
shear              0.002293
coverage           0.002872

In [12]:
ss_df = pd.merge(y, ss_df, left_index=True, right_index=True)
pca_df = pd.merge(y, pca_df, left_index=True, right_index=True)

In [13]:
ss_df.to_csv('StandarizedRunway32.csv', decimal = ',', sep = ';', index = False)
pca_df.to_csv('PCARunway32.csv', decimal = ',', sep = ';', index = False)

In [14]:
pd.DataFrame(r18_df.var())

                                  0
threshold_separation       6.631598
flight_wake                0.116166
diag_distance              9.820291
m4_speed                 115.382125
m4_altitude                4.631570
visibility            464117.930670
CAVOK                      0.249230
temperature               91.683831
qnh                       46.165327
variable                   0.030685
direction                  1.218392
knots                     24.115788
knotsVariability           7.239483
min_height_amount          0.843735
min_height            229096.983607
max_amount                 1.474141
max_amount_height     224630.370839
significantClouds          0.027707
anyClouds                  0.000000
Lluvia                     0.127693
Niebla                     0.009834
Tormenta                   0.012985
shear                      0.026668
coverage                   0.221446

In [15]:
X = r18_df.drop(['threshold_separation'], axis=1)
y = r18_df['threshold_separation']

In [16]:
# Estandarizacion
b = StandardScaler().fit_transform(X)
ss_df = pd.DataFrame(data = b, columns = X.columns)

In [17]:
# PCA Estandarizado
pca = PCA(n_components = 10)
pca_b = pca.fit_transform(ss_df)
pca_df = pd.DataFrame(data = pca_b, columns = ['C1','C2','C3','C4','C5','C6','C7','C8','C9','C10'])

In [18]:
ss_df = pd.merge(y, ss_df, left_index=True, right_index=True)
pca_df = pd.merge(y, pca_df, left_index=True, right_index=True)

In [19]:
ss_df.to_csv('StandarizedRunway18.csv', decimal = ',', sep = ';', index = False)
pca_df.to_csv('PCARunway18.csv', decimal = ',', sep = ';', index = False)